version: "3.1"

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5001:80
    environment:
      PMA_HOST: db
    networks:
      inner:
        ipv4_address: 10.5.0.5

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      inner:
        ipv4_address: 10.5.0.6

  web:
    image: hanna/php:8.2-apache
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      inner:
        ipv4_address: 10.5.0.7

networks:
  inner:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

